# Generated by Django 6.0.3 on 2026-04-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_employee_date_joined_alter_employee_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
