# Generated by Django 6.0.3 on 2026-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='referance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='relatives',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='management.employee'),
        ),
    ]
