# Generated by Django 6.0.3 on 2026-06-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_holiday_remove_employee_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshifthistory',
            name='shift_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeshifthistory',
            name='shift_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
