# Generated by Django 6.0.3 on 2026-07-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_employeeshifthistory_shift_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='management.employee')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['employee', 'effective_from'], name='management__employe_1c9050_idx'), models.Index(fields=['employee', 'effective_to'], name='management__employe_a769fa_idx')],
            },
        ),
    ]
