# Generated by Django 6.0.3 on 2026-10-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='relatives',
            field=models.ManyToManyField(blank=True, to='management.employee'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('register_user', 'User Registered'), ('create_admin_manager', 'Admin/Manager Created'), ('employee_create', 'Employee Created'), ('employee_update', 'Employee Updated'), ('employee_deactivate', 'Employee Deactivated'), ('employee_activate', 'Employee Activated'), ('employee_delete', 'Employee Deleted'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('role_change', 'Role Changed'), ('attendance_checkin', 'Attendance Check-In'), ('attendance_checkout', 'Attendance Check-Out'), ('attendance_manual_create', 'Manual Attendance Created'), ('attendance_update', 'Attendance Updated'), ('attendance_delete', 'Attendance Deleted'), ('leave_apply', 'Leave Applied'), ('leave_approve', 'Leave Approved'), ('leave_reject', 'Leave Rejected'), ('leave_delete', 'Leave Deleted'), ('overtime_create', 'Overtime Created'), ('overtime_approve', 'Overtime Approved'), ('overtime_reject', 'Overtime Rejected'), ('overtime_delete', 'Overtime Deleted'), ('shift_create', 'Shift Created'), ('shift_update', 'Shift Updated'), ('shift_delete', 'Shift Deleted'), ('shift_assign', 'Shift Assigned'), ('holiday_create', 'Holiday Created'), ('holiday_update', 'Holiday Updated'), ('holiday_delete', 'Holiday Deleted'), ('salary_update', 'Salary Updated'), ('other', 'Other Activity')], db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('employee', 'Employee Management'), ('user', 'User Management'), ('attendance', 'Attendance'), ('leave', 'Leave Management'), ('overtime', 'Overtime Management'), ('shift', 'Shift Management'), ('holiday', 'Holiday Management'), ('salary', 'Salary / Payroll'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='management__categor_2e684a_idx'), models.Index(fields=['action_type', '-created_at'], name='management__action__6b0b4e_idx'), models.Index(fields=['actor_username', '-created_at'], name='management__actor_u_32a07d_idx'), models.Index(fields=['target_model', 'target_id'], name='management__target__a6e01d_idx')],
            },
        ),
    ]
